{% set name = "xicam.plugins" %}
{% set version = "2.2.3" %}
{% set sha256 = "de6d70e1d72c1fd2371addb0acda888cd90c948542020259b2c401d061b7a745" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/synchrotrons/Xi-cam.plugins/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - appdirs
    - astropy
    - entrypoints
    - pyqt >=5
    - pyqtgraph
    - requests
    - signalslot
    - virtualenv
    - xicam.core
    - yapsy

about:
  home: https://github.com/synchrotrons/Xi-cam.plugins
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The CAMERA platform for synchrotron data management, visualization, and reduction.
  description: |
    The xicam.gui package contains all gui code of the Xi-cam platform, as part
    of the xicam namespace package. For the backend components, see
    "xicam.core".
