{% set name = "xicam.plugins" %}
{% set version = "2.1.11" %}
{% set sha256 = "456975a3485a7edccc222df46a95a98ba3fee6adbd8bbc6867cb52c13f6b21a6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/synchrotrons/Xi-cam.plugins/archive/{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - appdirs
    - astropy
    - entrypoints
    - fabio
    - intake-bluesky
    - pyqt >=5
    - requests
    - signalslot
    - virtualenv
    - xicam.core
    - yapsy

test:
  imports:
    - xicam.plugins

about:
  home: "https://github.com/synchrotrons/Xi-cam.plugins"
  license: "BSD 3-Clause"
  license_family: "BSD"
  license_file: LICENSE.md
  summary: "The CAMERA platform for synchrotron data management, visualization, and reduction."
  description: |
    The xicam.gui package contains all gui code of the Xi-cam platform, as part of the xicam namespace package. For the backend components, see "xicam.core".
  
